baseURL = 'https://www.drevanoorschot.nl/'
languageCode = 'en-gb'
title = "Dré van Oorschot"
author = "Dré van Oorschot"
copyright = "© 2023 - 2025 Dré van Oorschot"
theme = 'risotto'

[params.theme]
palette = "monokai"

[[params.socialLinks]]
icon = "fa-brands fa-github"
title = "GitHub"
url = "https://github.com/Drevanoorschot"


[[params.socialLinks]]
icon = "fa-solid fa-envelope"
title = "Email"
popupImage = "images/email.png"

[[params.socialLinks]]
icon = "fa-brands fa-discord"
title = "Discord"
popupText = "username: dre60noscope"

[params.about]
logo = "images/me.jpg"
title = "Contact"
description = "Reach out to me on the following platforms:"

sectionPagesMenu = "main"

[menu]

  [[menu.main]]
    identifier = "cv"
    name = "curriculum vitae"
    url = "/cv/"
    weight = 10
  [[menu.main]]
    identifier = "projects"
    name = "projects"
    url = "/projects/"
    weight = 10

[markup.goldmark.renderer]
unsafe = true

[markup]

  # Table of contents
  # Add toc = true to content front matter to enable
  [markup.tableOfContents]
    startLevel = 2
    endLevel   = 3
    ordered    = true

# SEO stuff
[sitemap]
  changefreq = "weekly"
  filename = "sitemap.xml"
  priority = 0.5
