baseURL = 'https://www.drevanoorschot.nl/'
languageCode = 'en-gb'
title = "Dré v. Oorschot"
author = "Dré van Oorschot"
copyright = "© 2023 Dré van Oorschot"
theme = 'risotto'

[params.theme]
palette = "monokai"

[[params.socialLinks]]
icon = "fa-brands fa-github"
title = "GitHub"
url = "https://github.com/Drevanoorschot"